/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#84d7ae",
        "on-secondary-fixed": "#001b3d",
        "on-primary-container": "#90e4ba",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4a7",
        "secondary-fixed-dim": "#aec7f6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#3f5881",
        "on-error-container": "#93000a",
        "primary-fixed": "#9ff4c9",
        "surface-container-highest": "#e4e4cc",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdad4",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d6e3ff",
        "inverse-primary": "#84d7ae",
        "outline-variant": "#bec9c1",
        "primary": "#004e34",
        "tertiary": "#8b0700",
        "surface-bright": "#fbfbe2",
        "on-tertiary-fixed": "#400100",
        "surface-container-high": "#eaead1",
        "secondary-container": "#b6d0ff",
        "surface-container": "#efefd7",
        "on-surface-variant": "#3f4943",
        "secondary": "#465f88",
        "surface-container-low": "#f5f5dc",
        "surface-dim": "#dbdcc3",
        "surface": "#fbfbe2",
        "on-tertiary-container": "#ffc5bb",
        "on-background": "#1b1d0e",
        "primary-container": "#006847",
        "on-surface": "#1b1d0e",
        "on-secondary-fixed-variant": "#2d476f",
        "surface-variant": "#e4e4cc",
        "error": "#ba1a1a",
        "background": "#fbfbe2",
        "on-primary": "#ffffff",
        "tertiary-container": "#b70c00",
        "on-tertiary-fixed-variant": "#920700",
        "on-primary-fixed-variant": "#005237",
        "outline": "#6f7a72",
        "inverse-surface": "#303221",
        "inverse-on-surface": "#f2f2d9",
        "surface-tint": "#096c4b",
        "on-primary-fixed": "#002114"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
